name: Build firmware

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up west
        uses: zmkfirmware/setup-west-action@main
        with:
          path: .github/actions/setup-west

      - name: Build firmware
        run: west build -s zmk/app -d build -b nice_nano_v2 -- -DSHIELD=trk

      - name: Upload firmware
        uses: actions/upload-artifact@v2
        with:
          name: trk_firmware
          path: build/zephyr/zmk.uf2
