name: Build firmware

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up west
        uses: zmkfirmware/setup-west-action@main

      - name: Build firmware
        run: |
          west build -d build/cl_studio -b nice_nano_v2 \
            -S studio-rpc-usb-uart -- -DSHIELD=trk -DCONFIG_ZMK_STUDIO=y

      - name: Upload firmware
        uses: actions/upload-artifact@v2
        with:
          name: trk_firmware
          path: build/zephyr/zmk.uf2